Allow for concurrent unpacking
zeit/pkg pull request #1830
Opened 2022-12-20 20:11 UTC by tecimovic

Fix for:
https://github.com/vercel/pkg/issues/1829

This addresses a specific problem, where a packaged executable which contains a shared
library, is unpacked concurrently across multiple executables around the same time.

2022-12-21 10:23 UTC, robertsLando requested changes

2022-12-21 15:32 UTC, tecimovic commented
@robertsLando : good suggestion, I added the wrapper function. Thanks.

2022-12-21 15:32 UTC, tecimovic commented on prelude/bootstrap.js
> +    }
Done.

2022-12-21 15:37 UTC, robertsLando commented on prelude/bootstrap.js
>      createDirRecursively(path.join(dir, '..'));
Cannot this also create the same error?

2022-12-21 16:17 UTC, robertsLando commented on prelude/bootstrap.js
>      createDirRecursively(path.join(dir, '..'));
Even if I'm more familiar with codebase I couldn't tell you what else could go wrong, BTW let's see how tests goes

2022-12-23 08:35 UTC, robertsLando approved these changes

2023-04-18 16:09 UTC, robertsLando approved these changes

2023-10-04 07:54 UTC, robertsLando commented
For anyone that is enterested in this project, giving that I don't receive any feedback from Vercel anymore, I created my own forks of both pkg and pkg-fetch:

[yao-pkg/pkg-fetch](https://github.com/yao-pkg/pkg-fetch)
[yao-pkg/pkg](https://github.com/yao-pkg/pkg)

If someone is interested in helping me create a PR or move your active PR to those repositories.

Thanks 🙏🏼

2024-01-03 01:38 UTC, closed without merging